sudo: false
language: python
python: 
    - "3.6"
env:
    - DJANGO_SETTINGS_MODULE=academic_integrity_tool_v2.settings.test
install:
    - pip install -r academic_integrity_tool_v2/requirements/base.txt
before_script:
    - cat academic_integrity_tool_v2/settings/secure.py.example | tee academic_integrity_tool_v2/settings/secure.py
script: 
    - python manage.py migrate --noinput
    - python manage.py test 
